theme: jekyll-theme-midnight
title: Modmail Setup Guide (Patreon)
markdown: kramdown
github:
  repository_url: https://github.com/kyb3r/modmail
  owner_url: https://github.com/kyb3r/modmail
  owner_name: the Modmail Team
